#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

// 主要函数定义
GOM(IMV_GetVersion, pFEv)                // void* func(void)  
GOM(IMV_EnumDevices, iFEpu)              // int func(void*, unsigned int)
GOM(IMV_CreateHandle, iFEpip)            // int func(void**, int, void*)
GOM(IMV_DestroyHandle, iFEp)             // int func(void*)
GOM(IMV_OpenEx, iFEpi)                   // int func(void*, int)
GOM(IMV_Close, iFEp)                     // int func(void*)
GOM(IMV_FeatureIsWriteable, iFEpp)       // int func(void*, const char*)
GOM(IMV_SetIntFeatureValue, iFEppL)      // int func(void*, const char*, int64_t)
GOM(IMV_GetIntFeatureValue, iFEppp)      // int func(void*, const char*, int64_t*)
GOM(IMV_GetIntFeatureMax, iFEppp)        // int func(void*, const char*, int64_t*)
GOM(IMV_GetIntFeatureMin, iFEppp)        // int func(void*, const char*, int64_t*)
GOM(IMV_GetIntFeatureInc, iFEppp)        // int func(void*, const char*, int64_t*)
GOM(IMV_SetDoubleFeatureValue, iFEppd)   // int func(void*, const char*, double)
GOM(IMV_GetDoubleFeatureValue, iFEppp)   // int func(void*, const char*, double*)
GOM(IMV_GetDoubleFeatureMax, iFEppp)     // int func(void*, const char*, double*)
GOM(IMV_GetDoubleFeatureMin, iFEppp)     // int func(void*, const char*, double*)
GOM(IMV_SetEnumFeatureValue, iFEppl)     // int func(void*, const char*, uint64_t)
GOM(IMV_GetEnumFeatureValue, iFEppp)     // int func(void*, const char*, uint64_t*)
GOM(IMV_ExecuteCommandFeature, iFEpp)    // int func(void*, const char*)
GOM(IMV_StartGrabbing, iFEp)             // int func(void*)
GOM(IMV_StopGrabbing, iFEp)              // int func(void*)
GOM(IMV_AttachGrabbing, iFEppp)          // int func(void*, void*, void*)
GOM(IMV_GetFrame, iFEppu)                // int func(void*, void*, unsigned int)
GOM(IMV_ReleaseFrame, iFEpp)             // int func(void*, void*)
