1 stdcall IMV_EnumDevices(ptr long)
2 stdcall IMV_CreateHandle(ptr long ptr)
3 stdcall IMV_DestroyHandle(ptr)
4 stdcall IMV_OpenEx(ptr long)
5 stdcall IMV_Close(ptr)
6 stdcall IMV_FeatureIsWriteable(ptr str)
7 stdcall IMV_SetIntFeatureValue(ptr str int64)
8 stdcall IMV_GetIntFeatureValue(ptr str ptr)
9 stdcall IMV_GetIntFeatureMax(ptr str ptr)
10 stdcall IMV_GetIntFeatureMin(ptr str ptr)
11 stdcall IMV_GetIntFeatureInc(ptr str ptr)
12 stdcall IMV_SetDoubleFeatureValue(ptr str double)
13 stdcall IMV_GetDoubleFeatureValue(ptr str ptr)
14 stdcall IMV_GetDoubleFeatureMax(ptr str ptr)
15 stdcall IMV_GetDoubleFeatureMin(ptr str ptr)
16 stdcall IMV_SetEnumFeatureValue(ptr str uint64)
17 stdcall IMV_GetEnumFeatureValue(ptr str ptr)
18 stdcall IMV_ExecuteCommandFeature(ptr str)
19 stdcall IMV_StartGrabbing(ptr)
20 stdcall IMV_StopGrabbing(ptr)
21 stdcall IMV_AttachGrabbing(ptr ptr ptr)
22 stdcall IMV_GetFrame(ptr ptr long)
23 stdcall IMV_ReleaseFrame(ptr ptr)
